
Version: v1
kind: Service
metadata:
          name: {{ .Release.Name }}
          spec:
                    type: {{ .Values.service.type }} 
                      ports:
                                - port: {{ .Values.service.port }}
                                    selector:
                                                app: {{ .Release.Name }}{{- include "react-app.selectorLabels" . | nindent 4 }}
